### ISSUE TITLE
Wiki Search Example will not cancel

### ISSUE THREAD

**Issue by deanius** [vuejs/vue-rx#101]
Hi - I'm very curious in using this project. But this looks like a bug:

Given:  Most searches should be canceled when a new search term is done, and that's what I take is the intention of using switchMap.
When: A search is performed
Expected: The old search is canceled.
Actual: Because of the use of jQuery and Promises, the Observable returned from `fetchTerm` will not be canceled when the search term changes.

I don't have screen shots yet, but based on the code, that's what I believe the behavior will be.

If the rxjs ajax operators were used, cancelability would be built in. And it's not a good example to use jQuery just for something that rxjs already has.

**Comment by deanius** [comment]
I'm guessing JQuery/JSONP was used because of Wikipedia CORS. The following is relevant to doing that with RxJS: https://github.com/ReactiveX/rxjs/issues/2095

**Comment by NataliaTepluhina** [comment]
I slightly changed the example in #102 
Should cancel search now :sweat_smile:

**Comment by deanius** [comment]
Wow @NataliaTepluhina - that covers everything - thanks for jumping on that!
