### ISSUE TITLE
BehaviorSubject.next is not a function.

### ISSUE THREAD

**Issue by kepoddx** [vuejs/vue-rx#103]
I tried to add a BehaviorSubject to a single file component but when I call next on it, I get an error "this.dataSet$.next is not a function". I also tried adding BehaviorSubject to the Vue.use(VueRx, { BehaviorSubject }.  What am I doing wrong?

export default {
 ....,
  subscriptions() {
    return {
      dataSet$: new BehaviorSubject({})
  }
} 

this.dataSet$.next(jsonArr) throws and error

**Comment by kepoddx** [comment]
So I can't use a BehaviorSubject?

**Comment by regou** [comment]
No.
I don’t know why you need a BehaviorSubject. $createObservableMethod convers function to Observable. Is this what you want?

Besides, If you don’t feel convenient enough, you can always use rx without vue-rx, Just use $subscribeTo to help you auto unsubscribe
