### ISSUE TITLE
v-stream data is not being updated in componentInstance

### ISSUE THREAD

**Issue by MariuszWitkowski** [vuejs/vue-rx#106]
v-stream data is not being updated in componentInstance

When i update array `rows` then my `data` in v-stream is not updated.

This work

```html
<div v-for="row in rows">
    <input type="checkbox" :id="row.id" v-stream:change="{ subject: change$, data: { id: row.id } }"/>
</div>
```

This not working

```html
<div v-for="row in rows">
    <Checkbox :id="row.id" v-stream:change="{ subject: change$, data: { id: row.id } }" />
</div>
```

I think this is problem in directive `v-stream`:

```javascript
  ...
  
  bind (el, binding, vnode) {
    ...

    if (!modifiers.native && vnode.componentInstance) {
      ...
    } else {
      ...

      // store handle on element with a unique key for identifying
      // multiple v-stream directives on the same node
      ;(el._rxHandles || (el._rxHandles = {}))[getKey(binding)] = handle
    }
  },
  ...
```

should be

```javascript
  ...
  
  bind (el, binding, vnode) {
    ...

    if (!modifiers.native && vnode.componentInstance) {
      ...
    } else {
      ...
    }
    // store handle on element with a unique key for identifying
    // multiple v-stream directives on the same node
    ;(el._rxHandles || (el._rxHandles = {}))[getKey(binding)] = handle
  },
  ...
```

then `data` in stream directive is correctly updated on replace `rows`

**Comment by briwa** [comment]
@MariuszWitkowski we were facing the same issue too. Do you mind making a PR for this? That would be great!

**Comment by regou** [comment]
@MariuszWitkowski @briwa The `v-stream` example (`example/counter.html` -> `<my-button/>`) works well, can any of you provide a running example in jsbin or runkit for us to diagnosis?

**Comment by briwa** [comment]
@regou Sorry for reaching out late. You can try it out here https://codesandbox.io/s/m531vow8rx.

1. Initially, `foo` is `{ bar: 0}`. If you click the first 4 buttons, it outputs the same thing.
2. Then, click the button that changes `foo` to `{bar: random number}`. 
3. Click the first 3 buttons, they output the same random number. The last button (`custom button with vue-rx`) would still output `{ bar: 0}`.

I saw that you've made a PR for this. Thanks a lot!
