### ISSUE TITLE
vue renderes before observable 

### ISSUE THREAD

**Issue by gotenxds** [vuejs/vue-rx#113]
Hello, I have this following piece of code:

```js
    subscriptions: () => ({
      character: getCurrentCharacter
    }),
```

and in my template: 
```
{{character.id}}
```

if I try and run the code I get 
`Cannot read property 'id' of undefined`

But if I change my template to 
```
{{character && character.id}}
```

it works fine, this means that in the first render the observable did not return the character buy then it did and caused a second render

**Comment by regou** [comment]
@gotenxds It’s Rxjs related expected behavior.
Try emit default value with`.startsWith( {} )`
