### ISSUE TITLE
How do we use this library with vue3 alpha 8?

### ISSUE THREAD

**Issue by roboticscm** [vuejs/vue-rx#122]
Dear, Team.
How do we use this library with vue3 alpha 8?

**Comment by chenxeed** [comment]
I guess a better question will be, will this library supports Vue 3?

**Comment by yyx990803** [comment]
https://github.com/vuejs/vue-rx/issues/120

If someone is interested in working on a long term RX integration for Vue 3 we'd be happy to audit and potentially adopt it as the official solution, but for now it's not very high priority for us.
