### ISSUE TITLE
typo in warning, and maybe a new name like vue-observable?

### ISSUE THREAD

**Issue by beeplin** [vuejs/vue-rx#13]
[Code here](https://github.com/vuejs/vue-rx/blob/master/vue-rx.js#L26) uses the old option name `rx` instead of `subscriptions`.

I understand that using `subscriptions` means supporting not only RxJS but any other observable libs. So maybe it needs a new name rather than `vue-rx`.

**Comment by yyx990803** [comment]
Agreed...
