### ISSUE TITLE
using $watchAsObservable, and using throw new Error() watch not work

### ISSUE THREAD

**Issue by nshusr** [vuejs/vue-rx#130]
using $watchAsObservable, and using throw new Error() watch not work, the watch will become invalid. Even if catchError is used, it will no longer watch. Is there a way to wake up this watch?

使用$watchAsObservable后，再使用throw new Error()抛出错误后，watch 就会失效，即使有使用catchError 它也将不再进行watch ，请问有没有办法继续执行这个watch，不去理那个error ，我自己在catchError 中弹出错误提示

LIVE preview: https://codesandbox.io/s/vue-rx-throw-error-j5m66?file=/src/App.vue

**Comment by regou** [comment]
Hello @nshusr 
It seems you want continuation on error, you need `catchError` and emit an `EMPTY` Observable in `catchError` callback
[See this answer](https://stackoverflow.com/a/38665803)
