### ISSUE TITLE
vue-observable (rx) 2.0 observations

### ISSUE THREAD

**Issue by zoomclub** [vuejs/vue-rx#14]
The addition of the new subscriptions option to a vm makes a huge difference, thanks Evan! There is now a place (sandbox) for observables to do their thing in. Using the subscriptions option it is possible to build any kind of observable while the method option remains for standard functions. Its a nice separation of concerns.

When I first encountered Vue and was learning the basics I saw an opportunity to bind RxJS directly into the Vue event system and I mentioned this in several issues here but never got any feedback on this idea. No one said a word but finally I came to the understanding that this binding could be achieved using a Vue Directive.

I suppose this directive could be added to this vue-observable plugin as well but I'm not even sure it is the most versatile idea anymore? Using RxJS alone (using fromEvent) it is possible to capture events from the DOM so why bother with the directive? Can someone tell me instead of me just always making what I consider positive suggestions!

Anyways, I just want to auto subscribe several observables when I create a component and capture their events as a streams. This looks like it is possible now so I can finally rest my battle weary head and enjoy the fruit of my quest for a good framework.

Based on feedback I'll kill this and the other issues I created and we can all move on in triumph :)

**Comment by yyx990803** [comment]
Sorry for missing your issue - I think I just didn't quite understand what you wanted at first glance. Do you have an example of what your desired usage would be like?

**Comment by zoomclub** [comment]
Gathering usage cases and relevant info. Need to head out to a rehearsal, will be back shortly...

**Comment by maple-leaf** [comment]
About this , I think there is a downside of `fromDOMEvent`. That's take a look of this code:

```
<ul><li v-for="item in list" @click="doSomeThing(item)"></li></ul>
```

Normally, just normal `doSomeThing` function should be ok, but if we want do some `debounce` or some `async` , Rx.js way would be best way here. How to deal with this with `fromDOMEvent` ?

**Comment by yyx990803** [comment]
@maple-leaf that's a valid issue! I think it's still possible to somehow hook up the template (and especially template-only variables like v-for iterators) with an observable source.

Maybe something like this? (rough idea)

``` html
<ul>
  <li v-for="item in list" @click="$toStream('itemClicks', item)"></li>
</ul>
```

``` js
subscriptions () {
  return {
    itemClicks: this.$fromStream('itemClicks').do(item => console.log(item))
  }
}
```

**Comment by zoomclub** [comment]
Having event sources from both fromDOMEvent in the subscription option and the template itself would cover pretty well all use cases. Stream and reactive loving devs will be in heaven!

**Comment by maple-leaf** [comment]
How about do the stream transforming with a modifier?

```
<ul>
  <li v-for="item in list" @click.event-stream="itemClicks(item)"></li>
</ul>
```

And the modifier will create a event-stream called 'itemClicks' in `$eventStream`. And we can use it like this:

```
this.$eventStream.itemClicks.subscribe(item => console.log(item));
this.$eventStream.itemClicks.subscribe(({ item, rest } => console.log(item, rest));
```

This will not going to break current `@click` usage, you just need a modifier if stream desired and remove it while stream is overhead.

And all event stream is in `$eventStream`, vue-rx can easily `unsubscribe` them when needed.

**Comment by zoomclub** [comment]
Have two alternatives here, the first still binding stream handling to the subscriptions option, while the later allowing the subscribe to happen anywhere. Both techniques are useful.

**Comment by regou** [comment]
Hey, @zoomclub  
I dont't think `$fromDOMEvent(selector,event)` is good enough.

@yyx990803 , I build a directive `vm-ob:click="click$"`, but the sourcecode are not elegant (view-model dirty hack). Any help?

[example](https://github.com/regou/vue-rx/blob/ob-dir/example/counter_dir.html)

[code](https://github.com/regou/vue-rx/blob/ob-dir/vue-rx.js#L142-L171)

**Comment by MVSICA-FICTA** [comment]
@regou Nice, just few things. 

• It would be useful to chain together multiple event types to capture them all in the observable, like `v-ob:mouseover.mouseout.mousemove="myMice$"`. 

• Why not a universal name for the directive? This then reflects that it is suitable for any stream library, something like `v-stream` would work. The name could also have an abbreviated version, $ instead of the usual @.

• Notice that the subscribing now happens in mounted, not in a subscriptions object. Seems okay 👍

**Comment by zoomclub** [comment]
@regou Nice, just a few points.

• It would be useful to be able to chain event types together to capture them all in the observable, like `v-ob:mouseover.mousemove.mouseup="myMice$".` 

• Why not call the directive v-stream, reflecting that it is also useful with any stream library? Maybe the abbreviated form could also be $ instead of the usual @.

• Noticed the subscribe is now in mounted and not in it's own subscription object. Seems okay to use observables and make subscriptions anywhere 👍

**Comment by regou** [comment]
@zoomclub 

- Keep it simple, users can just `Observable.merge` them
- ok
- This is the main issue: directive's `bind` happens after component's `created` lifecycal, but subscription defined in `create`(See sourcecode mixin),  which means unable to get `vm.myMice$` in `subscriptions`

**Comment by zoomclub** [comment]
@yyx990803 @regou What is the status of the new v-ob (v-stream) directive, can it be merged into vue-rx or is there some issue with it?

I'm streamlining my component method flow a bit these days and find that just working with RxJS in regular Vue methods works best (without using the subscriptions object). RxJS or Observables IMO are is just a part of ES7 anyways so I'd like to just work with them like standard JS. Looks like this is an option now, while still getting automatic unsubscribe handling?

**Comment by zoomclub** [comment]
To celebrate the resolution of this issue and the release of vue-rx 3.0 I'm closing this issue 🍾
