### ISSUE TITLE
Update to Rx.js 7 and adding Typescript?

### ISSUE THREAD

**Issue by PlexRipper** [vuejs/vue-rx#141]
Hi,

Seems this project is pretty much dead, I would be willing to update the Vue-rx to Rx.js 7 and possibly add typescript support. But only if someone can actually review and approve it, is that possible?

Cheers!

**Comment by regou** [comment]
Typing is currently supported.
Any MRs are welcomed.

**Comment by mdbetancourt** [comment]
> Hi,
> 
> Seems this project is pretty much dead, I would be willing to update the Vue-rx to Rx.js 7 and possibly add typescript support. But only if someone can actually review and approve it, is that possible?
> 
> Cheers!

you can use [@vueuse/rxjs](https://www.npmjs.com/package/@vueuse/rxjs)
