### ISSUE TITLE
Do i need to manually unsubscribe, if used in method

### ISSUE THREAD

**Issue by bagaskarala** [vuejs/vue-rx#153]
I'm using nuxt 2.17 with this package
- "rxjs": "^6.6.3"
- "vue-rx": "^6.2.0"

i'm wonder whether i need to unsubscribe from the observable or not, if i use it like below:
```
methods: {
    getOrders() {
      this.$orderService
        .getOrder()
        .pipe(map((res) => res.data))
        .subscribe((response) => {
          this.orders = response.data.orders;
        });
    },
  }
```

**Comment by regou** [comment]
Yes, you need to unsubscribe manually 
Try this: [beforeDestroy$](https://github.com/vuejs/vue-rx?tab=readme-ov-file#eventtoobservableevent)

**Comment by bagaskarala** [comment]
> Yes, you need to unsubscribe manually Try this: [beforeDestroy$](https://github.com/vuejs/vue-rx?tab=readme-ov-file#eventtoobservableevent)

@regou what will happen and the effect of this if i'm not unsubscribe? because i can call this method multiple time.
