### ISSUE TITLE
items in subscriptions cannot be watched?

### ISSUE THREAD

**Issue by beeplin** [vuejs/vue-rx#16]
```js
new Vue {
  subscriptions: {
    a: someObservable
  },
  watch: {
    a: function (v) {console.log (v); } // do something when 'a' changed. but not working.
  }
}
```

**Comment by zoomclub** [comment]
I'm not comfortable with this integration of RxJS in Vue, I depend on RxJS far to much for toying around. Automatic subscription behind the scenes is magical and limiting and leading to untested errors such as these. I think I'm just going to use the RxJS API where and when I want. 

I always liked this approach where everything is in the open:

import Vue from 'vue';
import {Observable, Subject} from 'rxjs';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/delay';
import axios from 'axios';

// This function is a typical Observable.fromEvent
// type of thing. Though specific to Vue JS and making state changes
function createObservable(cb) {
  let state = null;
  const subject = new Subject();
  cb(subject).subscribe(function (change) {
    change(state);
  });
  return function (arg) {
    state = this;
    subject.next(arg);
  }
}

new Vue({
  el: '#app',
  data: {
    posts: [],
    isLoading: false,
    error: null
  },
  methods: {

    // Instead of normal methods we make them expose an observable instead.
    // The returned observable(s) has to map to a function that receives the state
    // that can be changed. Pretty cool!
    fetchClick: createObservable((observable) => {
      const getPosts$ = observable
        .flatMap(() => Observable.fromPromise(axios.get('http://jsonplaceholder.typicode.com/posts')))
        .map(result => result.data)
        .share()

      const resetPosts$ = observable.map(() => state => state.posts = []);
      const startFetching$ = observable.map(() => state => state.isLoading = true);
      const stopFetching$ = getPosts$.map(() => state => state.isLoading = false);
      const setNewPosts$ = getPosts$
        .map(posts => state => state.posts = posts)
        .catch(err => state => state.error = err.message);

      return Observable.merge(
        resetPosts$,
        setNewPosts$,
        startFetching$,
        stopFetching$
      );
    })
  }
})
