### ISSUE TITLE
initialization timing still has problems.

### ISSUE THREAD

**Issue by beeplin** [vuejs/vue-rx#17]
Now the initialization runs in beforeCreate without messing up original `dataFn`. But this makes properties in `subscriptions` not able to use other properties in `data`, `computed`, `props`. 

That's problematic since in most times we need to do things like this:

```js
data: {
  a: 1
}
subscriptions: {
  b: someObservableMaker(this.a) // this maker takes this.a as param to make an observable.
}
```

I guess this would be the best way to achieve our goal (write in coffee):

```coffee
beforeCreate: ->
  obs = this.$options.subscriptions
  if typeof obs is 'function' 
    obs = obs.call this
  return if !obs
  for ob of obs # for each key in obs 
    # use {} value to take the position in advance. **Cannot be undefined**
    # has to be {} in order to be used by others during creating
    defineReactive this, ob, {} 

created: ->
  obs = this.$options.subscriptions
  if typeof obs is 'function' 
    obs = obs.call this
  return if !obs
  for ob of obs # for each key in obs 
     ... # do the converting job for this[obs]
```

**Comment by yyx990803** [comment]
Hmm, this is indeed tricky. Your suggestion wouldn't work because it's calling the `subscriptions` fn twice, and the first time it doesn't have access to `data` or `props` either.

**Comment by yyx990803** [comment]
2.1.1 reverted to use `created`. As a workaround for watching a subscription, you can just do that in `created` with `vm.$watch` instead of using the `watch` option. This might be patched in the future from Vue core, but for now I think it's a relatively trivial issue.

**Comment by beeplin** [comment]
I will go with the `.startWith` way. Thanks!

But just out of curiosity, as for the flaw of my previous suggestion:

> Your suggestion wouldn't work because it's calling the subscriptions fn twice, and the first time it doesn't have access to data or props either.

Can this be solved by give subscriptions functions that return observables rather than observables themselves?

```coffee
subscriptions: ->
  a: => someObservableMaker(this.someData)
  b: => anotherObservable(this.someProps)
```

I think making it functions would delay their actual execution, so running it for the first time in `beforeCreate` would have no problem even `this.someData` and `this.someProps` are used to make the observables.

Am I wrong?

(of course this would bring another unnecessary API change and I don't mean to actually deploy this method.)
