### ISSUE TITLE
FYI: `publish().refCount()` cannot be retried.

### ISSUE THREAD

**Issue by blesh** [vuejs/vue-rx#21]
I was just looking through your code, and I noticed [you're using `publish().refCount()` here](https://github.com/vuejs/vue-rx/blob/4d40a8200396d6c8d856e663dc11d01d919c7f95/vue-rx.js#L97)

This becomes problematic if something downstream causes an error and you want to reconnect the observable. something like...

```js
// Imagine the endpoint throws a 404 here.
o.$watchAsObservable('foo').switchMap(x => Observable.ajax.getJSON('http://endpoint/' + x)).retry(3)
```

It's a little edge-casey, honestly. And it can be easily worked around by moving the `retry` inside of the `switchMap`.

My first thought is you can solve this by replacing `.publish().refCount()` with `.share()`. They behave similarly, but `share` allows retries.

However, looking slightly more deeply, I think that what you're building on top of (`$watch`) is effectively multicast anyhow, so you probably don't need `publish().refCount()` in the first place, unless the underpinnings of `$watch` are particularly costly. It's really up to you.

Great work here, BTW!

**Comment by yyx990803** [comment]
Thanks for the tip! To be honest this was from a previous pull request and I don't think I fully understood what that entails ;) Looks like I can just remove that then.

**Comment by regou** [comment]
I use pub&ref incase someone call watchAsOb many times, but $watch is multicast as you said.
The latest watched value should immediately emitted even watch late
I suggest use `Rx.BehaviorSubject(vm[key])`

Anyway, library's behave should be consistent, so i don't pull a request to change this
