### ISSUE TITLE
obs in 'subscriptions' cannot be watched

### ISSUE THREAD

**Issue by beeplin** [vuejs/vue-rx#30]
```js
subscriptions () {
  return {
    a: SomeObservable
  }
},
watch: {
  'a': function () {console.log('a changed!')}
}
```

When `a` changes, it cannot be watched. This might be due to obs in `subscriptions` are defined with `Vue.util.defineReactive`, which makes it reactive, but not watchable.

If adding `test` to `data` and use `$subscribeTo` in `mounted` to link `test` with `SomeObservable`, it works. But it seems not very neat writing in this way.  I guess it would be best to put the obs into `data`.

**Comment by yyx990803** [comment]
This is already mentioned in the README as a caveat. You can simply do `this.$observables.a.subscribe(() => { ... })` in `created`.

**Comment by beeplin** [comment]
Got it. Thanks.
