### ISSUE TITLE
Error in directive stream bind hook: "TypeError: Cannot read property 'apply' of undefined"

### ISSUE THREAD

**Issue by zsimo** [vuejs/vue-rx#38]
Hi!

I'm facing a problem installing VueRx. 
By requiring entirely RxJs everything is fine:

```javascript
var Vue = require("vue");
var VueRx = require("vue-rx");

var Rx = require('rxjs');

Vue.use(VueRx, Rx);
```

But when I try to reduce the bundle size:
```javascript
var Vue = require("vue");
var VueRx = require("vue-rx");

var Rx = require('rxjs/Observable');
Rx.Subject = require('rxjs/Subject').Subject;
require('rxjs/add/operator/debounceTime');
require('rxjs/add/operator/map');
require('rxjs/add/operator/do');
require('rxjs/add/operator/mergeMap');

Vue.use(VueRx, Rx);
```
It's give me this error:
`Error in directive stream bind hook: "TypeError: Cannot read property 'apply' of undefined"`

Am I doing something wrong?

Thanks!

**Comment by regou** [comment]
Upgrade to 3.1.0, you'll see the warning 
_No 'fromEvent' method on Observable class._

```javascript
import 'rxjs/add/observable/fromEvent'
```

**Comment by zsimo** [comment]
Hi!

Great, adding 'fromEvent' works fine:

`require('rxjs/add/observable/fromEvent');`

Just as notification, it did not give me the 'No fromEvent'' warning  even if I'm using the 3.1 version.

Thank you very much!
