### ISSUE TITLE
Initial value of BehaviorSubject is not being rendered

### ISSUE THREAD

**Issue by dragantl** [vuejs/vue-rx#4]
Interesting behavior in Vue. You can see from example that BehaviorSubject is initialized with `false` and it is clear that `self[key] = value` works. However, the `vm` doesn't pick it up.

https://jsfiddle.net/ardoramor/L08jm958/2/

**Comment by yyx990803** [comment]
Looks like it's because the subscribe callback passed to BehaviorSubject is called synchronously.
