### ISSUE TITLE
Do i need unsubscribe

### ISSUE THREAD

**Issue by kinanson** [vuejs/vue-rx#41]
I have a question.I need unsubscribe in the angular.But i don't know in the vue.js how to do?Because Readme didn't say this.Maybe I don't need to worry this?

**Comment by regou** [comment]
If you returned your stream in subscribtion, Or using stream directive , vue-Rx will auto unsubscribe.
You can simply remember:"You have responsible for only those streams that called .subscribe() by you"

**Comment by kinanson** [comment]
thank you.I see

**Comment by regou** [comment]
Update:
you can handle auto unsub when using any of these :
- `vm.$subscribeTo`
- `subscriptions`
- `.takeUntil(vm.$eventToObservable('hook:beforeDestroy'))` (next release)
