### ISSUE TITLE
v-stream不支持vue自定义事件

### ISSUE THREAD

**Issue by xiangwan** [vuejs/vue-rx#44]
v-stream绑定事件时调用的 Rx.Observable.fromEvent.

vue-rx 源码 ->  https://github.com/vuejs/vue-rx/blob/master/src/directives/stream.js#L38

并不能监听vue自定义事件.

**Comment by regou** [comment]
What a coincidence! I just implemented https://github.com/vuejs/vue-rx/pull/45

**Comment by regou** [comment]
https://github.com/vuejs/vue-rx/releases/tag/v3.2.0
