### ISSUE TITLE
Needs types for vue-rx

### ISSUE THREAD

**Issue by TonyPythoneer** [vuejs/vue-rx#52]
Would you make `typings.json` for this repo?

**Comment by regou** [comment]
This is deprecated after ts2 I suppose? Install `@type` namespaced repo instead now.
vue-rx itself don't expose any method, in this case not sure how much we can benefit from it
Maybe you can provide other vue plugin examples that meant to be corporate with ts projects.
And pull requests are welcomed.

**Comment by oliverw** [comment]
`This is deprecated after ts2 I suppose? Install @type namespaced repo instead now.`

No, it is not. @types/<something> isn't automagically created. Someone has to author it and push it to NPM. The recommended way is to ship a <code>index.d.ts</code> with your library.

`vue-rx itself don't expose any method`

<code>$watchAsObservable</code> is not a method?

**Comment by oliverw** [comment]
Great work as usual. Thanks a lot!
