### ISSUE TITLE
Observable with params.

### ISSUE THREAD

**Issue by ionutt** [vuejs/vue-rx#66]
Hi,
   I am new to VUE ( I have an angular background ). Is there a way to and in the HTML something like this?

  <p>{{someObservable('value1')}}</p>
  <p>{{someObservable('value2')}}</p>

 I need to watch on the same component multiple subjects depending on the value that is pass from the function. 
  Thanks in advance.

**Comment by regou** [comment]
If you mean `someObservable('value1') | async` like angular
Then no. 
All async rendering ob on template have to pre-defined on `subscriptions`
Before vue support async filters. I don't find a better way but to handle these async rendering by updating data values in `$subscribeTo` -> `next` callback

**Comment by ionutt** [comment]
Thanks.
