### ISSUE TITLE
Is using the `subscribe` inside `subscriptions` is a good idea?

### ISSUE THREAD

**Issue by coun7zero** [vuejs/vue-rx#67]
I want to use a stream with `observableMethods` into `mounted () {` with `this.$subscribeTo` but then I have an error:
```
Property or method "foo" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See...
```

When I use that into `subscriptions` everything is all right but I have to subscribe that observable so is it a good place for that? Is using the `subscribe` inside `subscriptions` guarantee unsubscribe before component will be destroyed?

**Comment by regou** [comment]
Subscribe by your self with out vue-rx knowing is guaranteed **NOT** going to auto unsubscribe.

**Comment by regou** [comment]
BTW, You may use `takeUntil(beforeDestroy$)` to do auto unsub

**Comment by coun7zero** [comment]
@regou good point, thank you :)

**Comment by dews** [comment]
Use `takeUntil(this.$eventToObservable("hook:beforeDestroy"))`
