### ISSUE TITLE
Does not support feature Event Modifiers

### ISSUE THREAD

**Issue by pinghe** [vuejs/vue-rx#73]
Does not support feature Event Modifiers

v-stream:click.stop

https://vuejs.org/v2/guide/events.html#Event-Modifiers

**Comment by regou** [comment]
stop & prevent default you may you `do` operator for now
Others use `options: { once: true, passive: true, capture: true }`
https://github.com/vuejs/vue-rx/blob/master/README.md#v-stream-streaming-dom-events

**Comment by pinghe** [comment]
````
v-stream:click="plus$"

  domStreams: ['plus$'],
  subscriptions () {
    this.plus$
      .pipe(
        tap(x => {
          console.log(x.event)
          x.stopPropagation()
        }),
        catchError(err => {
          console.log('error: ', err)
        })
      )

output:
error:  TypeError: x.stopPropagation is not a function
````

**Comment by regou** [comment]
@pinghe `x.event.stopPropagation()`

**Comment by pinghe** [comment]
Need to add .native Modifier, otherwise the following error occurs
error:  TypeError: x.event.stopPropagation is not a function

**Comment by regou** [comment]
@pinghe `x.event.stopPropagation()` works fine without any error.

Can you provide a running example that can reproduce the issue?
