### ISSUE TITLE
This should not be using the UMD/Global version of RxJS

### ISSUE THREAD

**Issue by benlesh** [vuejs/vue-rx#79]
As the RxJS project lead, I *highly* recommend just installing `rxjs` (v6 preferred) and importing and using it as normal. Otherwise, there will be severe application size and performance penalties when using this library.

If you need help, I'm happy to do so.

This is related to my findings while helping review #78

**Comment by johnlindquist** [comment]
@benlesh it's not using the UMD bundle, `Rx` is a config object passed in when you `install` the plugin:

https://github.com/vuejs/vue-rx/blob/master/src/util.js#L5

**Comment by yyx990803** [comment]
The user can provide only the operators needed by importing them individually, see https://github.com/vuejs/vue-rx/blob/master/README.md#tips-for-reducing-bundle-size
