### ISSUE TITLE
Typescript definition not exporting properly

### ISSUE THREAD

**Issue by keego** [vuejs/vue-rx#89]
The docs mention importing like so
```ts
import Vue from 'vue'
import VueRx from 'vue-rx'

Vue.use(VueRx)
```

However this yields a TypeScript error: `TS1192: Module '...node_modules/vue-rx/types/index' has no default export`

I was able to work around this via
```ts
import Vue from 'vue'
import * as VueRx from 'vue-rx'

const vueRx: any = VueRx
Vue.use(vueRx.default)
```

And things seem to be working normally now.

Here's the relevant package versions I'm using:
```
  "rxjs": "^6.2.1",
  "vue": "^2.5.2",
  "vue-router": "^3.0.1",
  "vue-rx": "^6.0.0"
```

**Comment by printjs** [comment]
same problem

**Comment by kaorun343** [comment]
Hi.

Could you refer to this code?
https://github.com/vuejs/vue-rx/blob/master/types/test/index.ts

**Comment by keego** [comment]
@kaorun343 You're referring to lines [2](https://github.com/vuejs/vue-rx/blob/master/types/test/index.ts#L2) and [6](https://github.com/vuejs/vue-rx/blob/master/types/test/index.ts#L6) right? Does that test case work?

When I `import * as VueRx from 'vue-rx'` and `Vue.use(VueRx)`, VueRx still isn't used. As mentioned above, it only works if I `Vue.use(VueRx.default)`. If you `console.log('VueRx', { VueRx })` you'll see VueRx refers to a module with only a default export.

Exploring `node_modules/vue-rx` you can see the only export from `vue-rx.esm.js` is `export default VueRx`, so not sure why `node_modules/vue-rx/types/index.d.ts` says otherwise....

I've made a minimal repo to repro the issue [here](https://github.com/keego/vue-rx-issue). I just updated to the latest `@vue/cli` and created the project with the following options:
![screen shot 2018-07-18 at 11 37 35 am](https://user-images.githubusercontent.com/5094178/42902290-fe494846-8a82-11e8-9aeb-89f1e32f38d8.png)
I then ran 
```bash
yarn add rxjs@^6.2.1
yarn add vue@^2.5.2
yarn add vue-router@^3.0.1
yarn add vue-rx@^6.0.0
```
and made a minimal component to demonstrate vue-rx usage

Unless I've completely missed something, it seems like either (1) `vue-rx.esm.js` should be changed to export things differently, or (2) both the vue-rx docs and the vue-rx typings need to be updated. Personally, I prefer the (2) as the default export mechanics are simpler, cleaner, and more modern.

**Comment by yyx990803** [comment]
Open to a PR that fixes the typings :)

**Comment by keego** [comment]
@yyx990803 Well said :)
