### ISSUE TITLE
Why is immediate false by default?

### ISSUE THREAD

**Issue by dietergeerts** [vuejs/vue-rx#92]
When debugging why my component didn't work in a unit test, I found out that with `$watchAsObservable`, immediate is false by default. So that means that nothing got fired. I would have assumed that it would be true by default, as in most cases, that is what would be expected. 

So is there any good reason to have it false by default? And can this be changed?

**Comment by regou** [comment]
it ment to be consistent behavior with [vm-watch](
https://vuejs.org/v2/api/#vm-watch)

`vm.$watchAsObservable( 'a',  {immediate :true} )`
