### ISSUE TITLE
$subscribeTo won't cancel previous requests.

### ISSUE THREAD

**Issue by serkandemirel0420** [vuejs/vue-rx#97]
```
           import { ajax } from 'rxjs/ajax';
           const obs$ = ajax( `http://api` );


            globalThis.vm.$subscribeTo( obs$,
                ( success ) => {
                    console.log(success);
                }
                ,
                ( error ) => {
                    console.log('Error:',error);
                },
                ( complete ) => {
                    console.log('Completed!');
                }
            );
```

Am i doing something wrong here?

**Comment by regou** [comment]
This is a common misunderstanding about Observable streams
I think you are seeking to [Unsubscribable](https://rxjs-dev.firebaseapp.com/api/index/interface/Unsubscribable) or [switchMap](https://rxjs-dev.firebaseapp.com/api/operators/switchMap)

**Comment by serkandemirel0420** [comment]
"This is a prototype method added to instances. You can use it to subscribe to an observable, but let VueRx manage the dispose/unsubscribe." What does this mean in the documentation?

**Comment by regou** [comment]
@serkandemirel0420 It'll auto unsubscribe the stream when `beforeDestroy` the vm
